#!/usr/bin/env bash
# Block incoming traffic

sudo apt-get update -y && sudo apt-get install -y ufw

echo "y" | sudo ufw enable

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow required ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Show status
sudo ufw status verbose
