#!/usr/bin/env bash
# Install and configure Nginx to return "Holberton School"

apt-get update -y
apt-get install nginx -y

# Write custom response
echo "Holberton School for the win!" > /var/www/html/index.html

# Ensure nginx is running
service nginx start
