#!/usr/bin/env bash
# Installs nginx and adds a custom X-Served-By header with the server hostname

apt-get -y update
apt-get -y install nginx

sed -i '/server_name _;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

service nginx restart
