#!/usr/bin/env bash
# Nginx should be running and listening 
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
curl -i 0:80
