#!/usr/bin/env bash
# Install and configure Nginx web server

# Update package lists
apt-get update -y

# Install nginx
apt-get install -y nginx

# Ensure nginx is running
service nginx start

# Replace default index.html with required content
echo "Holberton School for the win!" > /var/www/html/index.html
