#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
